### ISSUE TITLE
Exception and broken sync after item deletion on the server

### ISSUE THREAD

**Issue by sualfred** [Montellese/xbmc#72]
Already reported on Slack.

To reproduce:

- Close Kodi
- Delete a series on the server
- Start Kodi and let the fast sync kick in

Exception:
```
2020-05-12 11:34:59.050 T:52696    INFO <general>: [mediaimporter.emby] Emby Media Import importer started
2020-05-12 11:34:59.051 T:52696    INFO <general>: [mediaimporter.emby] importing ['tvshow', 'season', 'episode'] items from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.072 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.072 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "Serien" view from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.077 T:52696    INFO <general>: [mediaimporter.emby] importing tvshow items from "HDR Serien" view from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)...
2020-05-12 11:34:59.089 T:52696    INFO <general>: [mediaimporter.emby] 1 previously imported tvshow items removed from "FREDFLIX" (emby://3212d5bb4b8e4c168a8ad4baf23fa8e6/)
2020-05-12 11:34:59.095 T:52696   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmcmediaimport' has no attribute 'MediaImportChangesetTypeRemoved'
                                                   Traceback (most recent call last):
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\importer.py", line 17, in <module>
                                                       importer.run(sys.argv)
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\lib\importer.py", line 986, in run
                                                       actionMethod(handle, options)
                                                     File "E:\Kodi\Kodi Media Import\portable_data\addons\mediaimporter.emby\lib\importer.py", line 819, in execImport
                                                       xbmcmediaimport.MediaImportChangesetTypeRemoved)
                                                   AttributeError: module 'xbmcmediaimport' has no attribute 'MediaImportChangesetTypeRemoved'
                                                   -->End of Python script error report<--
                                                   
```

**Comment by Montellese** [comment]
Since this issue is independent from Emby I moved it to my Kodi fork.

**Comment by sualfred** [comment]
Yes, can reproduce it. 
For testing I've deleted the db file, resynced, deleted a series on the server and faced the same issue.

**Comment by Montellese** [comment]
This will be fixed with new test builds.
